// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOCK_5xyeEf84QZNezh4uCNa1GU8cceqU',
    appId: '1:543617234015:android:e345f80559dffa3b7857ea',
    messagingSenderId: '543617234015',
    projectId: 'authentication-fbe51',
    storageBucket: 'authentication-fbe51.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wtbqKPCJfO3yl0_TIfiiPhWaFq43rQM',
    appId: '1:543617234015:web:436b591a095bab2a7857ea',
    messagingSenderId: '543617234015',
    projectId: 'authentication-fbe51',
    authDomain: 'authentication-fbe51.firebaseapp.com',
    storageBucket: 'authentication-fbe51.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkx5eWbR-cs7oOblAWqn1HaGtGy4-DRMQ',
    appId: '1:543617234015:ios:a44b3517a03f24927857ea',
    messagingSenderId: '543617234015',
    projectId: 'authentication-fbe51',
    storageBucket: 'authentication-fbe51.appspot.com',
    iosBundleId: 'com.example.new5raXo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkx5eWbR-cs7oOblAWqn1HaGtGy4-DRMQ',
    appId: '1:543617234015:ios:a44b3517a03f24927857ea',
    messagingSenderId: '543617234015',
    projectId: 'authentication-fbe51',
    storageBucket: 'authentication-fbe51.appspot.com',
    iosBundleId: 'com.example.new5raXo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9wtbqKPCJfO3yl0_TIfiiPhWaFq43rQM',
    appId: '1:543617234015:web:beaa849fba5d2e5b7857ea',
    messagingSenderId: '543617234015',
    projectId: 'authentication-fbe51',
    authDomain: 'authentication-fbe51.firebaseapp.com',
    storageBucket: 'authentication-fbe51.appspot.com',
  );

}